image: ndazeo/angularfire2

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REF_NAME-assets"

deploy:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - npm run build -- --prod
    - firebase use --token $FIREBASE_DEPLOY_KEY default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
